config/routes.rb
Dellamari::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :comentarios

  resources :pizzas

  resources :pizza_tipos

  resources :produtos

  root :to => 'produtos#index'
end

app/models/comentario.rb
class Comentario < ActiveRecord::Base
  attr_accessible :assunto, :autor, :comentario

  include Tire::Model::Search
  include Tire::Model::Callbacks

  def self.search params
		tire.search(load: true) do
			query { string params[:query], default_operator: "AND" } if params[:query].present?
			sort { by :updated_at, "desc" } if params[:query].blank?
			filter :range, created_at: {lte: Time.zone.now}
		end  	
  end

end

app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController

  def index
    @comentarios = Comentario.search params

    respond_to do |format|
      format.html 
      format.json { render json: @comentarios }
    end
  end

  def show
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      format.html 
      format.json { render json: @comentario }
    end
  end

  def new
    @comentario = Comentario.new

    respond_to do |format|
      format.html 
      format.json { render json: @comentario }
    end
  end
  
  def edit
    @comentario = Comentario.find(params[:id])
  end

  def create
    @comentario = Comentario.new(params[:comentario])

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render json: @comentario, status: :created, location: @comentario }
      else
        format.html { render action: "new" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comentario = Comentario.find(params[:id])

    respond_to do |format|
      if @comentario.update_attributes(params[:comentario])
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comentario = Comentario.find(params[:id])
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url }
      format.json { head :no_content }
    end
  end
end

app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% @comentario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :autor %><br />
    <%= f.text_field :autor %>
  </div>
  <div class="field">
    <%= f.label :assunto %><br />
    <%= f.text_field :assunto %>
  </div>
  <div class="field">
    <%= f.label :comentario %><br />
    <%= f.text_area :comentario %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render 'form' %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

app/views/comentarios/index.html.erb
<h1>Lista de comentarios</h1>

<%= form_tag comentarios_path, method: :get do %>
  <p>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Busca", name: nil %>
  </p>
<% end %>

<br />
<table class="table">
  <tr>
    <th>Autor</th>
    <th>Assunto</th>
    <th>Comentario</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @comentarios.each do |comentario| %>
  <tr>
    <td><%= comentario.autor %></td>
    <td><%= comentario.assunto %></td>
    <td><%= comentario.comentario %></td>
    <td><%= link_to 'Show', comentario %></td>
    <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
    <td><%= link_to 'Destroy', comentario, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= link_to 'New Comentario', new_comentario_path %>

app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render 'form' %>

<%= link_to 'Back', comentarios_path %>

app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Autor:</b>
  <%= @comentario.autor %>
</p>

<p>
  <b>Assunto:</b>
  <%= @comentario.assunto %>
</p>

<p>
  <b>Comentario:</b>
  <%= @comentario.comentario %>
</p>


<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>