config/routes.rb
Dellamari::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :comentarios

  resources :pizzas

  resources :pizza_tipos

  resources :produtos

  root :to => 'produtos#index'
end

app/models/pizza_tipo.rb
class PizzaTipo < ActiveRecord::Base
  attr_accessible :nome
end

app/controllers/pizza_tipos_controller.rb
class PizzaTiposController < ApplicationController
  # GET /pizza_tipos
  # GET /pizza_tipos.json
  def index
    @pizza_tipos = PizzaTipo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pizza_tipos }
    end
  end

  # GET /pizza_tipos/1
  # GET /pizza_tipos/1.json
  def show
    @pizza_tipo = PizzaTipo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pizza_tipo }
    end
  end

  # GET /pizza_tipos/new
  # GET /pizza_tipos/new.json
  def new
    @pizza_tipo = PizzaTipo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pizza_tipo }
    end
  end

  # GET /pizza_tipos/1/edit
  def edit
    @pizza_tipo = PizzaTipo.find(params[:id])
  end

  # POST /pizza_tipos
  # POST /pizza_tipos.json
  def create
    @pizza_tipo = PizzaTipo.new(params[:pizza_tipo])

    respond_to do |format|
      if @pizza_tipo.save
        format.html { redirect_to @pizza_tipo, notice: 'Pizza tipo was successfully created.' }
        format.json { render json: @pizza_tipo, status: :created, location: @pizza_tipo }
      else
        format.html { render action: "new" }
        format.json { render json: @pizza_tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pizza_tipos/1
  # PUT /pizza_tipos/1.json
  def update
    @pizza_tipo = PizzaTipo.find(params[:id])

    respond_to do |format|
      if @pizza_tipo.update_attributes(params[:pizza_tipo])
        format.html { redirect_to @pizza_tipo, notice: 'Pizza tipo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pizza_tipo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pizza_tipos/1
  # DELETE /pizza_tipos/1.json
  def destroy
    @pizza_tipo = PizzaTipo.find(params[:id])
    @pizza_tipo.destroy

    respond_to do |format|
      format.html { redirect_to pizza_tipos_url }
      format.json { head :no_content }
    end
  end
end

app/views/pizza_tipos/_form.html.erb
<%= form_for(@pizza_tipo) do |f| %>
  <% if @pizza_tipo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pizza_tipo.errors.count, "error") %> prohibited this pizza_tipo from being saved:</h2>

      <ul>
      <% @pizza_tipo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pizza_tipos/edit.html.erb
<h1>Editing pizza_tipo</h1>

<%= render 'form' %>

<%= link_to 'Show', @pizza_tipo %> |
<%= link_to 'Back', pizza_tipos_path %>

app/views/pizza_tipos/index.html.erb
<h1>Listing pizza_tipos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pizza_tipos.each do |pizza_tipo| %>
  <tr>
    <td><%= pizza_tipo.nome %></td>
    <td><%= link_to 'Show', pizza_tipo %></td>
    <td><%= link_to 'Edit', edit_pizza_tipo_path(pizza_tipo) %></td>
    <td><%= link_to 'Destroy', pizza_tipo, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pizza tipo', new_pizza_tipo_path %>

app/views/pizza_tipos/new.html.erb
<h1>Cadastrar tipo de Pizza</h1>

<%= render 'form' %>

<%= link_to 'Back', pizza_tipos_path %>

app/views/pizza_tipos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @pizza_tipo.nome %>
</p>


<%= link_to 'Edit', edit_pizza_tipo_path(@pizza_tipo) %> |
<%= link_to 'Back', pizza_tipos_path %>